webservice:
  image: nginxinc/nginx-unprivileged:latest
  hosts:
    - test.example.com
  replicas: 1
  port: 8080

  # nginx needs writable dirs when using readOnlyRootFilesystem
  volumes:
    - name: nginx-cache
      mountPath: /var/cache/nginx
      emptyDir: {}
    - name: nginx-run
      mountPath: /var/run
      emptyDir: {}
    - name: nginx-tmp
      mountPath: /tmp
      emptyDir: {}
