{{ $root := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{ if .Values.podSecurityStandard.enabled }}
    pod-security.kubernetes.io/enforce: {{ .Values.podSecurityStandard.level }}
    pod-security.kubernetes.io/audit: {{ .Values.podSecurityStandard.level }}
    pod-security.kubernetes.io/warn: {{ .Values.podSecurityStandard.level }}
{{ end }}
spec:
  replicas: {{ .Values.webservice.replicas }}
  revisionHistoryLimit: {{ .Values.webservice.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
{{ if .Values.webservice.topologySpreadConstraints }}
  topologySpreadConstraints:
{{ .Values.webservice.topologySpreadConstraints | toYaml | indent 4 }}
{{ end }}
{{ if .Values.webservice.strategy }}
  strategy:
{{ .Values.webservice.strategy | toYaml | indent 4 }}
{{ end }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
{{ if .Values.webservice.additionalLabels }}
{{ .Values.webservice.additionalLabels | toYaml | indent 8 }}
{{ end }}

{{ if .Values.webservice.annotations }}
      annotations:
{{ .Values.webservice.annotations | toYaml | indent 8 }}
{{ end }}
    spec:
{{ if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "serviceAccountName" . }}
{{ end }}
      automountServiceAccountToken: false
      enableServiceLinks: {{ .Values.webservice.enableServiceLinks }}
{{ if .Values.runtimeClassName }}
      runtimeClassName: {{ .Values.runtimeClassName }}
{{ end }}
{{ if .Values.webservice.hostAliases }}
      hostAliases:
{{ .Values.webservice.hostAliases | toYaml | indent 8 }}
{{ end }}
      securityContext:
{{- if .Values.webservice.securityContext }}
{{ .Values.webservice.securityContext | toYaml | indent 8 }}
{{- else }}
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
{{- end }}
{{ if .Values.webservice.dnsConfig }}
      dnsConfig:
{{ .Values.webservice.dnsConfig | toYaml | indent 8 }}
{{ end }}
{{ if .Values.webservice.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.webservice.terminationGracePeriodSeconds }}
{{ end }}
      containers:
        - name: {{ template "fullname" . }}
          image: {{ .Values.webservice.image }}
          securityContext:
{{- if .Values.webservice.containerSecurityContext }}
{{ .Values.webservice.containerSecurityContext | toYaml | indent 12 }}
{{- else }}
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
{{- end }}
          imagePullPolicy: {{ .Values.webservice.imagePullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.webservice.port }}
{{- if .Values.webservice.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.webservice.metrics.port }}
{{- end }}
{{ if .Values.webservice.command }}
          command:
{{ .Values.webservice.command | toYaml | indent 12 }}
{{ end }}
{{ if .Values.webservice.args }}
          args:
{{ .Values.webservice.args | toYaml | indent 12 }}
{{ end }}

{{ if .Values.webservice.env }}
          envFrom:
{{ if .Values.webservice.env.secret }}
            - secretRef:
                name: {{ template "fullname" . }}
{{ end }}
{{ if .Values.webservice.env.plaintext }}
            - configMapRef:
                name: {{ template "fullname" . }}
{{ end }}
{{ end }}

          resources:
{{- if .Values.webservice.resources }}
{{ .Values.webservice.resources | toYaml | indent 12 }}
{{- else }}
            limits:
              cpu: 500m
              memory: 512Mi
              ephemeral-storage: 2Gi
            requests:
              cpu: 100m
              memory: 128Mi
              ephemeral-storage: 1Gi
{{- end }}
{{ if .Values.webservice.livenessProbe }}
          livenessProbe:
{{ .Values.webservice.livenessProbe | toYaml | indent 12 }}
{{ end }}
{{ if .Values.webservice.readinessProbe }}
          readinessProbe:
{{ .Values.webservice.readinessProbe | toYaml | indent 12 }}
{{ end }}
{{ if .Values.webservice.startupProbe }}
          startupProbe:
{{ .Values.webservice.startupProbe | toYaml | indent 12 }}
{{ end }}
{{ if .Values.webservice.volumes }}
          volumeMounts:
{{ range .Values.webservice.volumes }}
{{ if .mountPath }}
            - mountPath: {{ .mountPath }}
              subPath: {{ .subPath }}
              name: {{ .name }}
{{ end }}
{{ end }}
{{ end }}

{{ if .Values.webservice.additionalContainers }}
{{ range .Values.webservice.additionalContainers }}
        - name: {{ .name }}
{{ .container | toYaml | indent 10 }}

{{ if .env}}
          envFrom:
{{ if .env.secret }}
            - secretRef:
                name: "{{ template "fullname" $root }}-{{ .name }}"
{{ end }}
{{ if .env.plaintext }}
            - configMapRef:
                name: "{{ template "fullname" $root }}-{{ .name }}"
{{ end }}
{{ end }}

{{ end }}
{{ end }}

{{ if .Values.webservice.nodeSelector }}
      nodeSelector:
{{ .Values.webservice.nodeSelector | toYaml | indent 10 }}
{{ end }}

{{ if .Values.webservice.affinity }}
      affinity:
{{ .Values.webservice.affinity | toYaml | indent 10 }}
{{ end }}

{{ if .Values.webservice.initContainers }}
      initContainers:
{{ range .Values.webservice.initContainers }}
        - name: {{ .name }}
{{ .container | toYaml | indent 10 }}

{{ if .env }}
          envFrom:
{{ if .env.secret }}
            - secretRef:
                name: "{{ template "fullname" $root }}-{{ .name }}"
{{ end }}
{{ if .env.plaintext }}
            - configMapRef:
                name: "{{ template "fullname" $root }}-{{ .name }}"
{{ end }}
{{ end }}

{{ end }}
{{ end }}

{{ if .Values.webservice.imagePullAuth }}
      imagePullSecrets:
        - name: {{ template "fullname" . }}-registry
{{ end }}

{{ if .Values.webservice.volumes }}
      volumes:
{{ range .Values.webservice.volumes }}

{{ if .storage }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ template "fullname" $root }}-{{ .name }}
{{ end }}

{{ if .configMap }}
        - name: {{ .name }}
          configMap:
            name: {{ .configMap.name }}
{{ end }}

{{ if .secret }}
        - name: {{ .name }}
          secret:
            secretName: {{ .secret.name }}
            optional: {{ .secret.optional }}
{{ end }}

{{ end }}

{{ end }}
