{{- define "dockerconfigjson" -}}
{{ printf "{\"auths\":{\"%s\":{\"Username\":\"%s\",\"Password\":\"%s\"}}}" .registry .username .password | b64enc | quote }}
{{- end }}
{{- if .Values.webservice.imagePullAuth }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ template "fullname" . }}-docker
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  .dockerconfigjson: {{ template "dockerconfigjson" .Values.webservice.imagePullAuth }}
{{- end }}