{{- define "sealedsecret" -}}
{{ $rangeItem := index . 0 }}
{{ with index . 1 }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
{{ if $rangeItem.name}}
  name: "{{ template "fullname" . }}-{{ $rangeItem.name }}"
{{ else }}
  name: "{{ template "fullname" . }}"
{{ end }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    # this is because the name is a deployment time parameter
    # consider also using "cluster-wide" if the namespace is also a parameter
    # please make sure you understand the implications, see README
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
  {{ range $key, $val := $rangeItem.env.secret }}
    {{ $key }}: {{ $val | quote }}
  {{ end }}
{{ end }}
{{- end -}}

{{ $root := . }}
{{ if and .Values.webservice.env.secret .Values.general.sealedSecrets }}
{{ template "sealedsecret" (list .Values.webservice $) }}
{{ end }}

{{ range .Values.webservice.additionalContainers}}
{{ if and (and .env .env.secret) $.Values.general.sealedSecrets }}
---
{{ template "sealedsecret" (list . $) }}
{{ end }}
{{ end}}

{{ range .Values.webservice.initContainers}}
{{ if and (and .env .env.secret) $.Values.general.sealedSecrets }}
---
{{ template "sealedsecret" (list . $) }}
{{ end }}
{{ end}}
