general:
  sealedSecrets: false

cronjob:
  schedule: "0 1 * * *"
  image:
    repository: "busybox"
    tag: "latest"
    pullPolicy: Always
  restartPolicy: OnFailure
  env:
    plaintext:
      TEST_VAR: "test-value"
