image:
  registry: registry.k8s.io
  repository: dns/k8s-dns-node-cache
  tag: 1.22.11
  pullPolicy: IfNotPresent

updateStrategy:
  rollingUpdate:
    maxUnavailable: 10%

resources:
  requests:
    cpu: 25m
    memory: 5Mi

upstream:
  selector:
    k8s-app: kube-dns
