{{- define "configmap" -}}
{{ $rangeItem := index . 0 }}
{{ with index . 1 }}
apiVersion: v1
kind: ConfigMap
metadata:
{{ if $rangeItem.name}}
  name: "{{ template "fullname" . }}-{{ $rangeItem.name }}"
{{ else }}
  name: "{{ template "fullname" . }}"
{{ end }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
{{ range $key, $val := $rangeItem.env.plaintext }}
  {{ $key }}: {{ $val | quote }}
{{ end }}
{{ end }}
{{- end -}}

{{ $root := . }}
{{ if .Values.cronJob.env.plaintext }}
{{ template "configmap" (list .Values.cronJob $) }}
{{ end }}

{{ range .Values.cronJob.additionalContainers }}
{{ if .env.plaintext }}
---
{{ template "configmap" (list . $) }}
{{ end }}
{{ end }}

{{ range .Values.cronJob.initContainers }}
{{ if .env.plaintext }}
---
{{ template "configmap" (list . $) }}
{{ end }}
{{ end }}