{{- define "dockerconfigjson" -}}
{{ printf "{\"auths\":{\"%s\":{\"Username\":\"%s\",\"Password\":\"%s\"}}}" .registry .username .password | b64enc | quote }}
{{- end -}}

{{ if .Values.cronJob.imagePullAuth }}
{{ if .Values.general.sealedSecrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: "{{ template "fullname" . }}-docker"
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    # this is because the name is a deployment time parameter
    # consider also using "cluster-wide" if the namespace is also a parameter
    # please make sure you understand the implications, see README
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    type: kubernetes.io/dockerconfigjson
  encryptedData:
    .dockerconfigjson: {{ .Values.cronJob.imagePullAuth.encrypted }}
{{ else }}
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: "{{ template "fullname" . }}-docker"
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  .dockerconfigjson: {{ template "dockerconfigjson" .Values.cronJob.imagePullAuth }}
{{ end }}
{{ end }}