{{- define "secret" -}}
{{ $rangeItem := index . 0 }}
{{ with index . 1 }}
apiVersion: v1
kind: Secret
metadata:
{{ if $rangeItem.name}}
  name: "{{ template "fullname" . }}-{{ $rangeItem.name }}"
{{ else }}
  name: "{{ template "fullname" . }}"
{{ end }}
  labels:
    app: {{ template "name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
stringData:
{{ range $key, $val := $rangeItem.env.secret }}
  {{ $key }}: {{ $val | quote }}
{{ end }}
{{ end }}
{{- end -}}


{{ if not .Values.general.sealedSecrets }}
{{ $root := . }}
{{ if .Values.cronJob.env.secret }}
{{ template "secret" (list .Values.cronJob $) }}
{{ end }}
{{ end }}

{{ range .Values.cronJob.additionalContainers }}
{{ if .env.secret }}
---
{{ template "secret" (list . $) }}
{{ end }}
{{ end }}

{{ range .Values.cronJob.initContainers }}
{{ if and .env.secret }}
---
{{ template "secret" (list . $) }}
{{ end }}
{{ end }}