apiVersion: v2
name: wik-node-local-dns
description: node-local-dns for ovh cluster
type: application
version: 0.1.0
appVersion: "0.1.0"

home: https://github.com/wikodit/charts
sources:
  - https://github.com/wikodit/charts

maintainers:
  - name: Wikodit
    url: https://github.com/wikodit
  - name: Anthony Domingue
    email: anthony@wikodit.fr
  - name: Jeremy Trufier
    email: jeremy@wikodit.fr

keywords:
  - wikodit
  - dns
  - nodelocaldns
  - coredns

annotations:
  artifacthub.io/license: MIT
