apiVersion: v1
description: Quick start for a all-in-one webservice
maintainers:
- email: anthony@wikodit.fr
  name: Anthony Domingue
- email: jeremy@wikodit.fr
  name: Jeremy Trufier
name: wik-webservice
version: 0.3.2
