apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-upstream" (include "common.names.fullname" . )}}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: {{ include "common.names.fullname" . }}
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "KubeDNSUpstream"
spec:
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.upstream.selector "context" $) | nindent 8 }}
