apiVersion: v1
description: Quick start for a all-in-one cronjob
maintainers:
- email: anthony@wikodit.fr
  name: Anthony Domingue
- email: jeremy@wikodit.fr
  name: Jérémy Trufier
name: wik-cronjob
version: 0.1.0
